language: ruby

os: osx

rvm:
  - 2.4

before_install:
  - brew update
  - brew --version
  - sudo gem install rubocop
  - mkdir -p /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade
  - cp -rf . /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade
  - cd /usr/local/Homebrew/Library/Taps/buo/homebrew-cask-upgrade
  - ls -la ../../../

script:
  - rubocop
  - brew cu -y
